/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import javax.naming.InitialContext;
import model.Student;
import serveur.FunctionContainer;
import utilitaire.Parser;

/**
 *
 * @author miker
 */
public class MyWindow extends javax.swing.JFrame {
    
    public void updateData() throws Exception {
        String filiereSelected = String.valueOf(filiereComboBox.getSelectedItem());
        String classeSelected = String.valueOf(classeComboBox.getSelectedItem());
        
        InitialContext ctx = new InitialContext();    
        FunctionContainer functionContainer = (FunctionContainer) ctx.lookup("michael");
        moyenneLabel.setText(String.valueOf(functionContainer.getMoyenneGenerale(filiereSelected, classeSelected)));
        ajourneLabel.setText(String.valueOf(functionContainer.getNombreAjourne(filiereSelected, classeSelected)));
        admisLabel.setText(String.valueOf(functionContainer.getNombreAdmis(filiereSelected, classeSelected)));
    }
    
    public void init() throws Exception {
        loadFilieres();
        loadClasses();
    }
    
    public void loadFilieres() throws Exception {
        InitialContext ctx = new InitialContext();    
        FunctionContainer functionContainer = (FunctionContainer) ctx.lookup("michael");
        List<String> uniqueFiliere = functionContainer.getAllFilieres();
        uniqueFiliere.forEach((filiere) -> {
            filiereComboBox.addItem(filiere);
        });
    }
    
    public void loadClasses() throws Exception {
        InitialContext ctx = new InitialContext();    
        FunctionContainer functionContainer = (FunctionContainer) ctx.lookup("michael");
        List<String> uniqueClasse = functionContainer.getAllClasses();
        uniqueClasse.forEach((classe) -> {
            classeComboBox.addItem(classe);
        }); 
    }

    /**
     * Creates new form MyWindow
     */
    public MyWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filiereComboBox = new javax.swing.JComboBox<>();
        classeComboBox = new javax.swing.JComboBox<>();
        AfficherButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        admisLabel = new javax.swing.JLabel();
        ajourneLabel = new javax.swing.JLabel();
        moyenneLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        filiereComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filieres" }));

        classeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Classes" }));

        AfficherButton.setText("Afficher");
        AfficherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AfficherButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Admis:");

        jLabel2.setText("Ajourné(s):");

        jLabel3.setText("Moyenne générale:");

        admisLabel.setText("vide");

        ajourneLabel.setText("vide");

        moyenneLabel.setText("vide");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(moyenneLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ajourneLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(admisLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(filiereComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(classeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(AfficherButton)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filiereComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(classeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AfficherButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(admisLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ajourneLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(moyenneLabel)
                    .addComponent(jLabel3))
                .addContainerGap(184, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AfficherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AfficherButtonActionPerformed
        // TODO add your handling code here:
        try {
            updateData();
        } catch(Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_AfficherButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AfficherButton;
    private javax.swing.JLabel admisLabel;
    private javax.swing.JLabel ajourneLabel;
    private javax.swing.JComboBox<String> classeComboBox;
    private javax.swing.JComboBox<String> filiereComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel moyenneLabel;
    // End of variables declaration//GEN-END:variables
}
